### ISSUE TITLE
[FEAT] 몬스터 구현

### ISSUE THREAD

**Issue by 0beanny** [khlee8688/2024-2-Sirius-Project#8]
## Issue

- 몬스터 타입에 따라 다르게 구현

## To-do
- [ ] 일반형 몬스터 구현
- [ ] 탱커형 몬스터 구현
- [ ] 원거리 몬스터 구현
- [ ] 발광(기행) 몬스터 구현
