### ISSUE TITLE
[FEAT] 추가 던지기 방식 구현 

### ISSUE THREAD

**Issue by yuykim** [khlee8688/2024-2-Sirius-Project#9]
## Issue

- 던지기 방식을 구현 

> 기본 : 포물선을 그리며 날라감

> 쿠나이 : 일직선으로 날라감

> 점착 폭탄 : 포물선으로 날라간 후, 제일 먼저 닿은 물체에 붙음, 후에 스페이스바를 누르면 터

## To-do

- [ ] 1번을 누른 후, c키를 누르면 '기본' 방식으로 투사체가 날라감

- [ ] 2번을 누른 후, c키를 누르면 '쿠나이' 방식으로 투사체가 날라감
- [ ] 3번을 누른 후, c키를 누르면 '점착 폭탄' 방식으로 날라감 (터짐)
